#!/bin/bash

# QuizHub Stress Testing - Quick Commands Reference
# Run this from the QuizHub root directory

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           QuizHub Stress Test Commands                      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "1️⃣  Comprehensive Stress Test (RECOMMENDED)"
echo "   Full test with user registration, admin promotion, quiz creation,"
echo "   quiz taking, leaderboards, and random endpoint access patterns"
echo ""
echo "   Command:"
echo "   python3 stress-tests/comprehensive-stress-test.py"
echo ""
echo "   Config: 40 users, 10 admins, 15 quizzes, 20 actions/user"
echo "   Expected: ~1000 requests in ~15 seconds (~45-70 RPS)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "2️⃣  User-Focused Stress Test"
echo "   Lighter test focusing on regular user activities"
echo "   (registration, login, browsing, leaderboards)"
echo ""
echo "   Command:"
echo "   python3 stress-tests/stress-test-users.py"
echo ""
echo "   Config: 50 users, 5 quiz views/user, 3 leaderboard views/user"
echo "   Expected: ~300 requests in ~1 second (~60-100 RPS)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "3️⃣  Apache Bench Load Test (if ab is installed)"
echo "   HTTP benchmarking tool for raw performance testing"
echo ""
echo "   Command:"
echo "   ./stress-tests/load-test-ab.sh"
echo ""
echo "   Install requirements:"
echo "   sudo apt-get install apache2-utils jq"
echo ""
echo "   Config: 50 concurrent, 1000 requests per endpoint"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📊 ENVIRONMENT VARIABLES (optional):"
echo ""
echo "   GATEWAY_URL - Override gateway URL (default: http://quizhub.local)"
echo "   Example: GATEWAY_URL=http://192.168.49.2 python3 stress-tests/comprehensive-stress-test.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🔍 CHECK OBSERVABILITY AFTER TESTS:"
echo ""
echo "   Jaeger (Distributed Tracing):"
echo "   kubectl port-forward -n observability svc/jaeger-query 16686:16686"
echo "   Open: http://localhost:16686"
echo ""
echo "   Kibana (Log Analysis):"
echo "   kubectl port-forward -n observability svc/kibana 5601:5601"
echo "   Open: http://localhost:5601"
echo ""
echo "   Grafana (Metrics & Dashboards):"
echo "   kubectl port-forward -n observability svc/grafana 3000:80"
echo "   Open: http://localhost:3000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "💡 TIPS:"
echo "   • Run comprehensive test first to generate data"
echo "   • Check Jaeger for traces from all services"
echo "   • Check Kibana for service-specific log indices"
echo "   • Press Ctrl+C to stop any running test"
echo ""

echo "🚀 Quick Start:"
echo "   python3 stress-tests/comprehensive-stress-test.py"
echo ""
